version: "3"

services:
  # API FastAPI
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - ./app/.env
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  # Celery worker
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery_app worker --loglevel=INFO
    restart: always
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - db

  # Celery beat
  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A app.core.celery_app beat --loglevel=INFO
    restart: always
    env_file:
      - ./app/.env
    depends_on:
      - redis

  # PostgreSQL
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

  # NGINX HTTP (initial)
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - api

  # Certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/lib/letsencrypt --quiet; sleep 12h & wait $${!}; done"

volumes:
  postgres_data:
  redis_data:
  certbot-etc:
  certbot-var:
