services:
  # API FastAPI
  api:
    build: .
    container_name: api
    restart: always
    env_file:
      - ./app/.env
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    networks:
      - app-network

  # Celery worker
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery_app.celery_app worker --loglevel=INFO
    restart: always
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - db
      - api

    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    networks:
      - app-network

  # Celery beat
  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A app.core.celery_app.celery_app beat --loglevel=INFO
    restart: always
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - api
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    networks:
      - app-network

  migrate:
    build: .
    command: alembic upgrade head
    depends_on:
      - db
    env_file:
      - ./app/.env
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    networks:
      - app-network

  # PostgreSQL
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  flower:
    image: mher/flower
    container_name: flower
    restart: always
    command: >
      celery --broker=redis://redis:6379/0
             flower --port=5555 --url_prefix=/flower
    depends_on:
      - redis
    expose:
      - "5555"
    networks:
      - app-network
  # Redis
  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - flower

    networks:
      - app-network


volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge

