"""update reading method

Revision ID: 53737a2adbec
Revises: 5e5c3f22328a
Create Date: 2025-09-04 20:28:18.513364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53737a2adbec'
down_revision: Union[str, Sequence[str], None] = '5e5c3f22328a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('photos', postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'photos')
    # ### end Alembic commands ###
