name: CI/CD - FastAPI Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login Docker
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build et push de l'image
      - name: Build and Push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/metersync:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      # 4️⃣ Déploiement sur VPS via SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/metrix
            git reset --hard origin/main
            git pull origin main
            # Pull la dernière image depuis Docker Hub
            sudo docker-compose pull
            # Relancer tous les conteneurs en production
            sudo docker-compose up -d --remove-orphans
            # Nettoyage optionnel
            sudo docker system prune -af
