name: Test Docker Login

on:
  push:
    branches: [ "main" ]

jobs:
  docker-login-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Docker Login Test
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify login
        run: |
          echo "Docker login successful!"
          docker info | grep Username
